categories:
  - title: ":boom: Breaking changes"
    labels:
      - breaking
  - title: ":fire: Removed"
    label: removed
  - title: ⚠️ Deprecated
    label: deprecated
  - title: ":sparkles: New features and improvements"
    labels:
      - enhancement
  - title: 🐛 Bug Fixes
    labels:
      - bug
  - title: 📝 Documentation updates
    label: documentation
  - title: 📦 Dependency updates
    label: dependencies
  - title: 👻 Maintenance
    label: chore
  - title: 🚦 Tests
    labels:
      - test
exclude-labels:
  - skip-changelog

template: |
  <!-- Optional: add a release summary here -->
  Changes in release
  $CHANGES
replacers:
  - search: '@dependabot-preview'
    replace: '@dependabot'